project:
  title: "NHSRpresentations"
  render: 
    - "*.qmd"
    - "!*.md"
embed-resources: true
format:
  revealjs:
    footer: "<https://postcard.nhsrcommunity.com/>"
    code-link: true
    preview-links: true
title-slide-attributes: 
  data-background-color: "#43464B"
brand: _brand.yml
